//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Spatial;
using Elements.Validators;
using Elements.Serialization.JSON;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements
{
    #pragma warning disable // Disable all warnings

    /// <summary>An element wrapping a 2d grid input</summary>
    [Newtonsoft.Json.JsonConverter(typeof(Elements.Serialization.JSON.JsonInheritanceConverter), "discriminator")]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class GridAxisControl2d : GeometricElement
    {
        [Newtonsoft.Json.JsonConstructor]
        public GridAxisControl2d(Grid2dInput @grid, Vector3 @roughPosition, Transform @transform = null, Material @material = null, Representation @representation = null, bool @isElementDefinition = false, System.Guid @id = default, string @name = null)
            : base(transform, material, representation, isElementDefinition, id, name)
        {
            this.Grid = @grid;
            this.RoughPosition = @roughPosition;
            }
        
        // Empty constructor
        public GridAxisControl2d()
            : base()
        {
        }
    
        /// <summary>A 2d grid</summary>
        [Newtonsoft.Json.JsonProperty("Grid", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Grid2dInput Grid { get; set; }
    
        /// <summary>For identity purposes</summary>
        [Newtonsoft.Json.JsonProperty("RoughPosition", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Vector3 RoughPosition { get; set; }
    
    
    }
}