//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.21.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------
using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Spatial;
using Elements.Validators;
using Elements.Serialization.JSON;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace Elements
{
    #pragma warning disable // Disable all warnings

    /// <summary>A simplified schema for a 1d grid used for a special geometry input</summary>
    [Newtonsoft.Json.JsonConverter(typeof(Elements.Serialization.JSON.JsonInheritanceConverter), "discriminator")]
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    public partial class Grid1dInput 
    {
        [Newtonsoft.Json.JsonConstructor]
        public Grid1dInput(Polyline @curve, IList<Vector3> @splitPoints, Grid1dInputSubdivisionMode? @subdivisionMode, SubdivisionSettings @subdivisionSettings)
        {
            this.Curve = @curve;
            this.SplitPoints = @splitPoints;
            this.SubdivisionMode = @subdivisionMode;
            this.SubdivisionSettings = @subdivisionSettings;
            }
        
        // Empty constructor
        public Grid1dInput()
        {
        }
    
        /// <summary>The base curve for the grid</summary>
        [Newtonsoft.Json.JsonProperty("Curve", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Polyline Curve { get; set; }
    
        /// <summary>The points at which the grid is split</summary>
        [Newtonsoft.Json.JsonProperty("SplitPoints", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<Vector3> SplitPoints { get; set; }
    
        /// <summary>How is this curve subdivided</summary>
        [Newtonsoft.Json.JsonProperty("SubdivisionMode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public Grid1dInputSubdivisionMode? SubdivisionMode { get; set; } = Elements.Grid1dInputSubdivisionMode.Manual;
    
        /// <summary>What parameters drive the subdivision?</summary>
        [Newtonsoft.Json.JsonProperty("SubdivisionSettings", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public SubdivisionSettings SubdivisionSettings { get; set; }
    
    
    }
}